import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  // Color base para estados seleccionados/activos
  // (más azul que el indigo anterior)
  // Nota: se usa como literal en estilos porque StyleSheet no permite variables reactivas.
  container: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 150,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    marginTop: 8,
    paddingHorizontal: 16,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#fff',
    flex: 1,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  syncWarningCard: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginBottom: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: 'rgba(245, 87, 108, 0.85)',
  },
  syncWarningText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
    flex: 1,
  },
  // Tabs
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    borderRadius: 25,
    padding: 4,
    alignItems: 'center',
  },
  tabContainerFloating: {
    position: 'absolute',
    left: 16,
    right: 16,
  },
  tab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 25, // Aumentamos un poco el radio
    gap: 8,
    // Eliminamos background de base para evitar superposiciones
  },
  tabActive: {
    backgroundColor: 'rgba(57, 108, 240, 0.4)', // Un poco más opaco para ocultar defectos de fondo
    borderRadius: 25, // REDUNDANTE Y CRITICO
    overflow: 'hidden', // CRITICO
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 0, // Quitamos elevación del tab activo para simplificar renderizado
    borderWidth: 1, // Añadimos un borde sutil para definir mejor la forma
    borderColor: 'rgba(255,255,255,0.2)'
  },
  tabText: {
    fontSize: 16,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.8)',
  },
  tabTextActive: {
    color: '#fff',
    fontWeight: '700',
  },
  // Estado vacío transparente
  emptyStateTransparent: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 60,
    marginTop: 40,
  },
  emptyStateTextTransparent: {
    color: 'rgba(255,255,255,0.5)',
    textAlign: 'center',
    fontSize: 18,
    marginTop: 20,
    fontWeight: '500',
  },
  // Card de Alarma
  alarmCard: {
    borderRadius: 24,
    // Eliminamos padding
    marginBottom: 16,
    marginHorizontal: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
    backgroundColor: 'transparent', // Fondo transparente crucial
    // Eliminamos border width y color aquí, se maneja en el gradiente o hijo
  },
  alarmCardNoShadow: { // Nuevo estilo para quitar sombra
    elevation: 0,
    shadowOpacity: 0,
    shadowColor: 'transparent',
  },
  alarmCardGradient: {
    borderRadius: 24, // Debe coincidir con alarmCard
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.4)',
    overflow: 'hidden', // Asegura que el contenido (como efectos de toque) no se salga
  },
  alarmCardInactive: {
    borderColor: 'rgba(255, 255, 255, 0.15)', // Borde más sutil
  },
  alarmInfo: {
    flex: 1,
  },
  alarmTime: {
    fontSize: 34,
    fontWeight: '800',
    color: '#1f2340',
    letterSpacing: 1,
  },
  alarmMedName: {
    fontSize: 19,
    fontWeight: '700',
    color: '#667eea',
    marginTop: 6,
  },
  alarmDose: {
    fontSize: 15,
    color: '#5a5f7a',
    marginTop: 4,
    fontWeight: '500',
  },
  daysContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 8,
    gap: 4,
  },
  dayBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: 'rgba(102, 126, 234, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(102, 126, 234, 0.2)',
  },
  dayBadgeInactive: {
    backgroundColor: 'rgba(150, 150, 160, 0.1)',
    borderColor: 'rgba(150, 150, 160, 0.2)',
  },
  dayBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#667eea',
  },
  dayBadgeTextInactive: {
    color: '#8a8d9e',
  },
  alarmActions: {
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: 10,
  },

  // Toggle animado (reemplaza Switch)
  toggleHit: {
    paddingVertical: 6,
    paddingHorizontal: 4,
    borderRadius: 999,
  },
  togglePressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
  },
  toggleDisabled: {
    opacity: 0.55,
  },
  toggleTrack: {
    width: 46,
    height: 26,
    borderRadius: 13,
    padding: 2,
    justifyContent: 'center',
    borderWidth: 1,
  },
  toggleTrackOn: {
    backgroundColor: 'rgba(102, 126, 234, 0.95)',
    borderColor: 'rgba(102, 126, 234, 0.35)',
    shadowColor: '#667eea',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
  },
  toggleTrackOff: {
    backgroundColor: 'rgba(120, 120, 140, 0.28)',
    borderColor: 'rgba(0, 0, 0, 0.08)',
  },
  toggleThumb: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 5,
  },
  actionButtonsRow: {
    flexDirection: 'row',
    marginTop: 12,
    gap: 8,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 14,
    // Fondo transparente solicitado
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    // Sin borde ni fondo gris
  },
  iconButtonDelete: {
     // Fondo transparente
    backgroundColor: 'transparent',
  },
  // Estilos para cuando la alarma está inactiva
  // Se verán en gris para indicar que no resaltan tanto, pero siguen siendo funcionales
  iconButtonInactive: {
     backgroundColor: 'transparent',
  },
  pillBadge: {
    backgroundColor: 'rgba(102, 126, 234, 0.12)',
    borderColor: 'rgba(102, 126, 234, 0.3)',
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
  },
  pillBadgeInactive: {
    backgroundColor: 'rgba(200, 200, 200, 0.15)',
    borderColor: 'rgba(200, 200, 200, 0.25)',
  },
  pillBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#667eea',
  },
  timeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  mutedText: {
    color: '#7b7b8a',
  },
  deleteButton: {
    padding: 8,
    marginTop: 10,
  },
  // Floating Button
  fab: {
    position: 'absolute',
    right: 25,
    width: 68,
    height: 68,
    borderRadius: 34,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#667eea',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 12,
    overflow: 'hidden',
  },
  fabTouchable: {
    width: '100%',
    height: '100%',
    borderRadius: 34,
  },
  fabGradient: {
    flex: 1,
    width: '100%',
    height: '100%',
    borderRadius: 34,
    justifyContent: 'center',
    alignItems: 'center',
  },

  // Toast (mensaje animado de creado/actualizado)
  toastWrap: {
    paddingHorizontal: 16,
    marginTop: 10,
    marginBottom: 6,
  },
  toastCard: {
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 14,
    elevation: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  toastIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(255,255,255,0.18)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  
  // Estilos de Audio Picker
  pickAudioButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#f0f4ff',
      padding: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#dce4ff',
  },
  pickAudioTitle: {
      color: '#333',
      fontWeight: '600',
      fontSize: 16,
  },
  pickAudioSubtitle: {
      color: '#999',
      fontSize: 13,
      marginTop: 2,
  },
  scrubberContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
  },
  scrubberTime: {
      width: 45,
      fontSize: 14,
      fontWeight: '600',
      color: '#667eea',
  },
  previewContainer: {
      alignItems: 'center',
      marginTop: 15,
  },
  previewButtonBig: {
      flexDirection: 'row',
      backgroundColor: '#667eea',
      paddingVertical: 10,
      paddingHorizontal: 24,
      borderRadius: 25,
      alignItems: 'center',
      gap: 8,
      shadowColor: "#667eea",
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.3,
      shadowRadius: 4.65,
      elevation: 8,
  },
  previewButtonPlaying: {
      backgroundColor: '#ff5f6d',
  },
  previewButtonText: {
      color: '#fff',
      fontWeight: 'bold',
      fontSize: 16,
  },
  
  // Library Modal Styles
  toneItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: '#f8f9fa',
      padding: 12,
      borderRadius: 12,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: '#eee',
  },
  toneItemSelected: {
      borderColor: '#667eea',
      backgroundColor: '#eff2ff',
  },
  toneIcon: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: '#e0e7ff',
      alignItems: 'center',
      justifyContent: 'center',
  },
  toneName: {
      fontSize: 16,
      color: '#333',
  },
  toneDuration: {
      fontSize: 12,
      color: '#999',
      marginTop: 2,
  },
  addToneButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 16,
      marginTop: 10,
      borderWidth: 2,
      borderColor: '#e0e7ff',
      borderRadius: 12,
      borderStyle: 'dashed',
  },
  addToneButtonText: {
      marginLeft: 8,
      fontSize: 16,
      fontWeight: '600',
      color: '#667eea',
  },
  noteText: {
      textAlign: 'center',
      color: '#aaa',
      fontSize: 12,
      marginTop: 20,
      fontStyle: 'italic',
  },
  toastTextWrap: {
    flex: 1,
  },
  toastTitle: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 2,
  },
  toastMessage: {
    color: 'rgba(255,255,255,0.92)',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(16, 10, 34, 0.6)',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  modalContent: {
    backgroundColor: '#fdfbff',
    borderRadius: 28,
    padding: 26,
    maxHeight: '86%',
    width: '100%',
    borderWidth: 1,
    borderColor: 'rgba(118, 75, 162, 0.22)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 18,
    elevation: 16,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(118, 75, 162, 0.15)',
  },
  modalTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#2f2a4a',
  },
  inputGroup: {
    marginBottom: 24,
  },
  inputLabel: {
    fontSize: 17,
    color: '#555',
    marginBottom: 10,
    fontWeight: '700',
  },
  textInput: {
    backgroundColor: '#f8f8f8',
    borderRadius: 14,
    padding: 16,
    fontSize: 16,
    borderWidth: 2,
    borderColor: '#e8e8e8',
    color: '#333',
  },
  textInputError: {
    borderColor: '#ef4444',
  },
  errorText: {
    marginTop: 6,
    fontSize: 12,
    color: '#ef4444',
    fontWeight: '700',
  },
  labelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  optionalTag: {
    fontSize: 12,
    color: '#7b7b8a',
    fontWeight: '700',
  },
  // Reloj Circular
  clockContainer: {
    alignItems: 'center',
    marginVertical: 20,
  },
  clockFace: {
    backgroundColor: '#f8f8ff',
    borderWidth: 3,
    borderColor: '#2563EB',
    position: 'relative',
    shadowColor: '#2563EB',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  clockNumber: {
    position: 'absolute',
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.85)',
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    zIndex: 5,
    elevation: 6,
  },
  clockNumberSelected: {
    backgroundColor: '#2563EB',
  },
  clockNumberText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#333',
  },
  clockNumberTextSelected: {
    color: '#fff',
    fontWeight: '800',
  },
  clockHand: {
    position: 'absolute',
    height: 4,
    backgroundColor: '#2563EB',
    borderRadius: 2,
    shadowColor: '#2563EB',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 2,
    zIndex: 2,
  },
  clockHandDot: {
    position: 'absolute',
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#2563EB',
    borderWidth: 2,
    borderColor: '#fff',
    shadowColor: '#2563EB',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 3,
    zIndex: 3,
  },
  clockCenter: {
    position: 'absolute',
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#667eea',
    borderWidth: 3,
    borderColor: '#fff',
    shadowColor: '#667eea',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 4,
    left: '50%',
    top: '50%',
    marginLeft: -9,
    marginTop: -9,
    zIndex: 10,
  },
  digitalDisplay: {
    marginTop: 20,
    backgroundColor: '#667eea',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 20,
    shadowColor: '#667eea',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  digitalTime: {
    fontSize: 32,
    fontWeight: '800',
    color: '#fff',
    letterSpacing: 2,
  },
  // Selector Hora/Minuto
  clockModeSelector: {
    flexDirection: 'row',
    backgroundColor: '#f0f0f0',
    borderRadius: 12,
    padding: 4,
    marginBottom: 16,
  },
  clockModeButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 10,
  },
  clockModeButtonActive: {
    backgroundColor: '#667eea',
  },
  clockModeText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#999',
  },
  clockModeTextActive: {
    color: '#fff',
    fontWeight: '700',
  },
  // Botón Guardar
  saveButton: {
    marginTop: 24,
    borderRadius: 18,
    overflow: 'hidden',
    shadowColor: '#667eea',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 8,
  },
  saveButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
    gap: 10,
  },
  saveButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  saveHintText: {
    marginTop: 10,
    textAlign: 'center',
    color: '#4b5563',
    fontSize: 13,
    fontWeight: '600',
  },
  chipsRowWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  weekSquaresWrap: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 6,
  },
  weekSquare: {
    flex: 1,
    minWidth: 0,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#f8f8f8',
    borderWidth: 1,
    borderColor: '#e8e8e8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  weekSquareActive: {
    backgroundColor: 'rgba(37, 99, 235, 0.16)',
    borderColor: '#2563EB',
  },
  weekSquareText: {
    fontSize: 12,
    color: '#555',
    fontWeight: '800',
  },
  weekSquareTextActive: {
    color: '#2563EB',
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: '#f2f2f6',
    borderWidth: 1,
    borderColor: '#e3e3eb',
  },
  chipActive: {
    backgroundColor: 'rgba(37, 99, 235, 0.14)',
    borderColor: '#2563EB',
  },
  chipText: {
    fontSize: 14,
    color: '#555',
    fontWeight: '600',
  },
  chipTextActive: {
    color: '#2563EB',
    fontWeight: '700',
  },
  twoFieldRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  
  // Dosis Styles
  doseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  doseInput: {
    flex: 0.4, 
    textAlign: 'center',
    height: 52, // Match picker height
  },
  unitChipsRow: {
    display: 'none', // Hidden now
  },
  unitChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    backgroundColor: '#f1f5f9',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  unitChipActive: {
    backgroundColor: '#667eea',
    borderColor: '#667eea',
  },
  unitChipText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748b',
  },
  unitChipTextActive: {
    color: '#fff',
  },

  smallFieldBlock: {
    flex: 1,
  },
  smallTextInput: {
    paddingVertical: 12,
    textAlign: 'center',
  },
  smallFieldHint: {
    marginTop: 6,
    fontSize: 12,
    color: '#7b7b8a',
    fontWeight: '800',
    textAlign: 'center',
  },
  rowInline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  dropdown: {
    marginTop: 10,
    height: 52,
    borderRadius: 14,
    backgroundColor: '#f8f8f8',
    borderWidth: 2,
    borderColor: '#e8e8e8',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dropdownPressed: {
    opacity: 0.92,
  },
  dropdownError: {
    borderColor: '#ef4444',
  },
  dropdownText: {
    fontSize: 16,
    color: '#333',
    fontWeight: '700',
  },
  dropdownPlaceholder: {
    color: '#999',
  },
  pickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    paddingHorizontal: 16,
    justifyContent: 'center',
    paddingBottom: 18,
  },
  pickerCard: {
    backgroundColor: '#fff',
    borderRadius: 22,
    padding: 16,
  },
  pickerTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#333',
    marginBottom: 12,
    textAlign: 'center',
  },
  pickerOptionsWrap: {
    gap: 10,
  },
  pickerOption: {
    height: 52,
    borderRadius: 16,
    backgroundColor: '#f8f8f8',
    borderWidth: 1,
    borderColor: '#e8e8e8',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pickerOptionSelected: {
    backgroundColor: 'rgba(37, 99, 235, 0.12)',
    borderColor: '#2563EB',
  },
  pickerOptionText: {
    fontSize: 15,
    color: '#333',
    fontWeight: '800',
  },
  pickerOptionTextSelected: {
    color: '#2563EB',
  },
  pickerCloseButton: {
    marginTop: 14,
    height: 46,
    borderRadius: 16,
    backgroundColor: '#667eea',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickerCloseText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 14,
  },
  rowInlineBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  inlineLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#555',
  },
  selectedTimeLabel: {
    fontSize: 20,
    fontWeight: '800',
    color: '#333',
  },
  configureButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#667eea',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
  },
  configureButtonText: {
    color: '#fff',
    fontWeight: '700',
  },
  // Selector de tiempo con TextInput
  timePickerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8f9ff',
    borderRadius: 20,
    padding: 20,
    marginTop: 10,
    gap: 12,
  },
  timePickerColumn: {
    alignItems: 'center',
    gap: 8,
  },
  timeInput: {
    minWidth: 70,
    paddingVertical: 16,
    paddingHorizontal: 20,
    backgroundColor: '#fff',
    borderRadius: 16,
    fontSize: 32,
    fontWeight: '800',
    color: '#667eea',
    textAlign: 'center',
    borderWidth: 2,
    borderColor: '#667eea',
    shadowColor: '#667eea',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 3,
  },
  timePickerSeparator: {
    fontSize: 36,
    fontWeight: '700',
    color: '#2563EB',
    marginBottom: 20,
  },
  timePickerLabel: {
    fontSize: 13,
    color: '#2563EB',
    fontWeight: '600',
    marginTop: 4,
  },
  periodSelector: {
    flexDirection: 'column',
    gap: 8,
    marginLeft: 8,
  },
  periodButton: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: 'rgba(37, 99, 235, 0.12)',
    borderWidth: 2,
    borderColor: 'rgba(37, 99, 235, 0.35)',
    minWidth: 50,
    alignItems: 'center',
  },
  periodButtonActive: {
    backgroundColor: '#2563EB',
    borderColor: '#2563EB',
  },
  periodText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#2563EB',
  },
  periodTextActive: {
    color: '#fff',
  },
  clockModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  clockModalCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 20,
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 10,
  },
  clockModalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#333',
    marginBottom: 12,
    textAlign: 'center',
  },
  acceptButton: {
    marginTop: 12,
    backgroundColor: '#667eea',
    paddingVertical: 12,
    borderRadius: 14,
    alignItems: 'center',
  },
  acceptButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
  },

  // Modal de Alerta (Estilo Logout)
  modalAlertOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  modalAlertContent: {
    backgroundColor: '#fff',
    borderRadius: 28,
    padding: 28,
    width: '100%',
    maxWidth: 360,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.3,
    shadowRadius: 30,
    elevation: 20,
  },
  modalAlertIconContainer: {
    marginBottom: 20,
  },
  modalAlertIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(245, 87, 108, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: 'rgba(245, 87, 108, 0.2)',
  },
  modalAlertTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#333',
    marginBottom: 12,
    textAlign: 'center',
  },
  modalAlertMessage: {
    fontSize: 15,
    color: '#666',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 28,
  },
  modalAlertButtons: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  modalAlertCancelButton: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 14,
    backgroundColor: '#f0f0f0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalAlertCancelText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#666',
  },
  modalAlertConfirmButton: {
    flex: 1,
    borderRadius: 14,
    overflow: 'hidden',
    shadowColor: '#f5576c',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 8,
  },
  modalAlertConfirmGradient: {
    flexDirection: 'row',
    paddingVertical: 14,
    paddingHorizontal: 20,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  modalAlertConfirmText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#fff',
  },

  // Modal Añadir Recordatorio (Profesional)
  modalAddOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    padding: 20,
  },
  modalAddContent: {
    borderRadius: 24,
    padding: 24,
    maxHeight: '80%',
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 20,
  },
  modalAddTitle: {
    fontSize: 22, 
    fontWeight: '800', 
    marginBottom: 24, 
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  modalAddList: {
    maxHeight: 400,
  },
  modalAddItem: {
    padding: 16, 
    borderRadius: 16, 
    marginBottom: 12,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  modalAddCloseButton: {
    marginTop: 20, 
    padding: 16, 
    alignItems: 'center', 
    borderRadius: 16,
    backgroundColor: 'rgba(120,120,120, 0.1)',
  },
  modalAddCloseText: {
    fontWeight: '700',
    fontSize: 16,
  },
});
